#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xrandr --output DP-2 --right-of DVI-I-1
bspc monitor DVI-I-1 -d browser dc+sptfy terminal 4 5
bspc monitor DP-2 -d code videos 8 9 10

bspc config border_width         2
bspc config window_gap           2

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

polybar &
bspc desktop -f ^1
brave &
sleep 1
bspc desktop -f ^6
kitty &
sleep 1
bspc desktop -f ^2
bspc config split_ratio          0.40
spotify &
sleep 1
discord &
sleep 5
bspc config split_ratio          0.50

