#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xrandr --output DP-2 --right-of DVI-I-1 --mode 2560x1440 --rate 143.97
bspc monitor DVI-I-1 -d browser spotify discord 4 5
bspc monitor DP-2 -d code stuff 8 9 10

bspc config border_width         2
bspc config window_gap           2

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Have Zathura behave normally
bspc rule -a Zathura state=tiled

polybar &
bspc desktop -f ^6
kitty &
sleep 1
bspc desktop -f ^1
brave &
sleep 3
bspc desktop -f ^2
spotify &
sleep 2
bspc desktop -f ^3
discord &

